# MXNet 入门

In [1]:
from mxnet import nd

# 创建行向量
x = nd.arange(12)
print(x)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>


In [2]:
# 数组形状
print(x.shape)

(12,)


In [3]:
# 元素总个数
print(x.size)

12


In [4]:
# 修改形状
print(x.reshape((3,4)))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>


In [6]:
# 修改形状 使用-1 进行推导
print(x.reshape((2,-1)))
print(x.reshape((-1,3)))


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
<NDArray 2x6 @cpu(0)>

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
<NDArray 4x3 @cpu(0)>


In [7]:
# 张量（多维数组）
print(nd.zeros((2,3,4)))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>


In [8]:
# 生成正态分布随机值
print(nd.random.normal(0,1,shape=(3,4)))


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.558071   -0.5459446  -2.3556297 ]
 [ 0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 3x4 @cpu(0)>


# MXNet 中 autograd 模块求梯度

In [10]:
from mxnet import autograd, nd

x = nd.arange(4).reshape((4, 1))
print(f"x={x}")

# 申请存储梯度所需要的内存
x.attach_grad()

# 为了减少计算和内存开销，默认条件下MXNet不会记录用于求梯度的计算。我们需要调用record函数来要求MXNet记录与求梯度有关的计算
with autograd.record():
    y = 3 * nd.dot(x.T, x)
    print(f"y={y}")

# 通过调用backward函数自动求梯度
b = y.backward()
print(f"b={b}")

print(f"x.grad={x.grad}")

x=
[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>
y=
[[42.]]
<NDArray 1x1 @cpu(0)>
b=None
x.grad=
[[ 0.]
 [ 6.]
 [12.]
 [18.]]
<NDArray 4x1 @cpu(0)>


# 训练模式和预测模式

从上面可以看出，在调用record函数后，MXNet会记录并计算梯度。此外，默认情况下autograd还会将运行模式从预测模式转为训练模式。这可以通过调用is_training函数来查看。

In [11]:
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())

False
True
